name: Daily README Update

on:
  schedule:
    - cron: '30 10 * * 1-5'
  
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Add startup delay to avoid rate limits
      run: |
        sleep $((RANDOM % 31))
    
    - name: Run README updater
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      run: |
        python update_readme.py
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        git add README.md
        git commit -m "🤖 Daily AI sentence extension - $(date +'%Y-%m-%d')"
        git push
    
    - name: No changes to commit
      if: steps.verify-changed-files.outputs.changed == 'false'
      run: |
        echo "No changes detected in README.md"
